version: '2.1'

services:
  localstack:
    container_name: ${CONTAINER_NAME}
    image: localstack/localstack
    hostname: ${HOSTNAME}
    network_mode: bridge
    ports:
      - "4566:4566"
    environment:
      - EDGE_PORT=4566
      - SERVICES=${SERVICES}
      - REGION=${REGION}
      - AWS_DEFAULT_REGION=${REGION}
      - AWS_ACCESS_KEY_ID=fake-key-id
      - AWS_SECRET_ACCESS_KEY=fake-secret-access-key
    volumes:
    - "./entrypoint.d:/docker-entrypoint-initaws.d"
